#make_classification

In [ ]:
from sklearn.datasets import make_classification
import numpy as np

# X, Y = make_classification(n_samples=1000, n_features=2, n_informative=2, n_redundant=0, n_repeated=0, n_classes=2, n_clusters_per_class=2,class_sep=2,flip_y=0,weights=[0.9,0.1], random_state=17)
X, Y = make_classification(n_samples=1000, n_classes=2, weights=[0.9,0.1])
X.shape, Y.shape, np.bincount(Y)

((1000, 20), (1000,), array([896, 104]))

#load_files with sklearn

In [1]:
!unzip dataset.zip

Archive:  dataset.zip
   creating: dataset/
   creating: dataset/dogs/
  inflating: dataset/dogs/dog01.jpeg  
  inflating: dataset/dogs/dog02.jpeg  
   creating: dataset/cats/
  inflating: dataset/cats/cat03.jpeg  
  inflating: dataset/cats/download.jpeg  
  inflating: dataset/cats/cat02.jpeg  


In [9]:
from sklearn.datasets import load_files

In [10]:
image_set = load_files(container_path='./dataset', load_content=True)
image_set

{'DESCR': None,
 'data': [b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\t\x06\x07\x13\x13\x12\x15\x13\x13\x12\x15\x16\x15\x15\x17\x17\x17\x17\x17\x16\x15\x15\x16\x16\x17\x15\x15\x15\x17\x17\x15\x16\x16\x15\x18\x1d( \x18\x1a&\x1d\x15\x15!1!%)+...\x17 383-7(-.+\x01\n\n\n\x0e\r\x0e\x1a\x10\x10\x1a+% %-------------------.------------------------------\xff\xc0\x00\x11\x08\x00\xa8\x01,\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1c\x00\x00\x02\x02\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x05\x04\x06\x00\x02\x07\x01\x08\xff\xc4\x00@\x10\x00\x01\x03\x02\x04\x03\x05\x04\x06\n\x02\x02\x03\x00\x00\x00\x01\x00\x02\x11\x03!\x04\x121A\x05Qa\x06"q\x81\x91\x132\xa1\xb1BRb\xc1\xd1\xf0\x07\x14#Cr\x82\x92\xa2\xb2\xe1\x15\xf13\xc2cs\x83\xff\xc4\x00\x19\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x00\x04\x05\xff\xc4\x00!\x11\x00\x02\x02\x02\x03\x00\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x11\x0

In [16]:
import numpy as np
datas = np.array(image_set['data'])

In [18]:
type(image_set.data[1]), type(datas), datas[1]

(bytes,
 numpy.ndarray,
 b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\t\x06\x07\x12\x13\x12\x15\x12\x12\x12\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x15\x17\x15\x16\x16\x15\x15\x15\x15\x18\x1d( \x18\x1a%\x1b\x15\x15!1!%)+...\x17\x1f383,7(-.+\x01\n\n\n\x0e\r\x0e\x1a\x10\x10\x17-\x1d\x1d%------------------------------+--.----------------\xff\xc0\x00\x11\x08\x00\x9f\x01>\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x02\x05\x06\x01\x00\x07\xff\xc4\x00>\x10\x00\x01\x03\x03\x02\x04\x04\x03\x06\x04\x05\x03\x05\x00\x00\x00\x01\x00\x02\x11\x03\x04!\x121\x05AQa\x06"q\x81\x132\x91BR\xa1\xb1\xc1\xd1\x14#b\xf0\x07r\x92\xe1\xf13C\x82\x15\x174\x83\xa2\xff\xc4\x00\x19\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\xff\xc4\x00\x1f\x11\x01\x01\x00\x02\x03\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x01\x02\x1

#compute_class_weight

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
weights = compute_class_weight('balanced', np.unique(Y), Y)
class_weight_01 = dict(enumerate(weights))
class_weight_02 = {0: weights[0], 1: weights[1]}
np.unique(Y), class_weight_01, class_weight_02

(array([0, 1]),
 {0: 0.5580357142857143, 1: 4.8076923076923075},
 {0: 0.5580357142857143, 1: 4.8076923076923075})

#K-Fold

In [ ]:
kfold = KFold(6, True, 10)
# enumerate splits
for train, test in kfold.split(data):
	print('train: %s, test: %s' % (data[train], data[test]))

train: [0.1 0.2 0.4 0.5 0.6], test: [0.3]
train: [0.1 0.2 0.3 0.4 0.5], test: [0.6]
train: [0.2 0.3 0.4 0.5 0.6], test: [0.1]
train: [0.1 0.2 0.3 0.5 0.6], test: [0.4]
train: [0.1 0.2 0.3 0.4 0.6], test: [0.5]
train: [0.1 0.3 0.4 0.5 0.6], test: [0.2]


In [ ]:
# sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)
# scikit-learn k-fold cross-validation
from numpy import array
from sklearn.model_selection import KFold
# data sample
data = array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
# prepare cross validation
kfold = KFold(3, True, 1)
# enumerate splits
for train, test in kfold.split(data):
	print('train: %s, test: %s' % (data[train], data[test]))

train: [0.1 0.4 0.5 0.6], test: [0.2 0.3]
train: [0.2 0.3 0.4 0.6], test: [0.1 0.5]
train: [0.1 0.2 0.3 0.5], test: [0.4 0.6]


#Cross validation

In [ ]:
import pandas
import numpy as np

dataset = pandas.read_csv('boston_df.csv')
X = dataset.drop(['RAD'], axis=1)
y = dataset['RAD']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)

from sklearn.model_selection import KFold
from sklearn.svm import SVC
best_svr = SVC(kernel='rbf')
scores = []
cv = KFold(n_splits=10, random_state=42, shuffle=True)
for train_index, test_index in cv.split(X):
    # print("Train Index: ", train_index, "\n")
    # print("Test Index: ", test_index)
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    best_svr.fit(X_train, y_train)
    scores.append(best_svr.score(X_test, y_test))

print('KFold mean score : ',np.mean(scores))
# best_svr = SVR(kernel='rbf')
from sklearn.model_selection import cross_validate
cv_score = cross_validate(best_svr, X, y, cv=10, scoring='f1_weighted')
# score = cross_val_predict(best_svr, X, y, cv=10)
print('cross_val_predict mean score : ',np.mean(cv_score['test_score']))   
# score

KFold mean score :  0.6107843137254901
cross_val_predict mean score :  0.4961521992781203


#numpy.argmax

In [ ]:
import numpy as np
list = [[20, 21, 12],[13, 14, 15]]
x = np.asarray(list)
x

array([[20, 21, 12],
       [13, 14, 15]])

In [ ]:
np.argmax(x), np.argmax(x, axis=0), np.argmax(x, axis=1)

(1, array([0, 0, 1]), array([1, 2]))

In [ ]:
import numpy as np
import pandas as pd

#Use sklearn

##Load Dataset Titanic from csv

In [ ]:
train = pd.read_csv('titanic_train.csv')
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
pd_titanic = train.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])

In [ ]:
pd_titanic.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
pd_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
np_array = pd_titanic.values
np_array

array([[0, 3, 'male', ..., 0, 7.25, 'S'],
       [1, 1, 'female', ..., 0, 71.2833, 'C'],
       [1, 3, 'female', ..., 0, 7.925, 'S'],
       ...,
       [0, 3, 'female', ..., 2, 23.45, 'S'],
       [1, 1, 'male', ..., 0, 30.0, 'C'],
       [0, 3, 'male', ..., 0, 7.75, 'Q']], dtype=object)

In [ ]:
pd.DataFrame(np_array).head()

0  1       2   3  4  5        6  7
0  0  3    male  22  1  0     7.25  S
1  1  1  female  38  1  0  71.2833  C
2  1  3  female  26  0  0    7.925  S
3  1  1  female  35  1  0     53.1  S
4  0  3    male  35  0  0     8.05  S

In [ ]:
# type(np_array[:,3:4]), np_array[:,3:4]

##SimpleImputer with sklearn

In [ ]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
imputer = imputer.fit(np_array[:,3:4])

In [ ]:
np_array[:,3:4] = imputer.transform(np_array[:,3:4])

##Scaler

In [ ]:
# from sklearn.preprocessing import RobustScaler
# # Scaling..
# scaler = RobustScaler()
# X = scaler.fit_transform(X)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
standardScaler = StandardScaler()
np_array_scaler = np_array
np_array_scaler

array([[0, 3, 'male', ..., 0, 7.25, 'S'],
       [1, 1, 'female', ..., 0, 71.2833, 'C'],
       [1, 3, 'female', ..., 0, 7.925, 'S'],
       ...,
       [0, 3, 'female', ..., 2, 23.45, 'S'],
       [1, 1, 'male', ..., 0, 30.0, 'C'],
       [0, 3, 'male', ..., 0, 7.75, 'Q']], dtype=object)

In [ ]:
np_array_scaler[:,5:6] = standardScaler.fit_transform(np_array_scaler[:,5:6])
np_array_scaler

array([[0, 3, 'male', ..., -0.4736736092984604, 7.25, 'S'],
       [1, 1, 'female', ..., -0.4736736092984604, 71.2833, 'C'],
       [1, 3, 'female', ..., -0.4736736092984604, 7.925, 'S'],
       ...,
       [0, 3, 'female', ..., 2.0089333664952354, 23.45, 'S'],
       [1, 1, 'male', ..., -0.4736736092984604, 30.0, 'C'],
       [0, 3, 'male', ..., -0.4736736092984604, 7.75, 'Q']], dtype=object)

##LabelEncoder with sklearn

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelEncoder = LabelEncoder()

In [ ]:
np_array_labeling = np_array_scaler
pd.DataFrame(np_array_labeling).head()

0  1       2   3  4         5        6  7
0  0  3    male  22  1 -0.473674     7.25  S
1  1  1  female  38  1 -0.473674  71.2833  C
2  1  3  female  26  0 -0.473674    7.925  S
3  1  1  female  35  1 -0.473674     53.1  S
4  0  3    male  35  0 -0.473674     8.05  S

In [ ]:
np_array_labeling[:,2] = labelEncoder.fit_transform(np_array_labeling[:,2])
pd.DataFrame(np_array_labeling).head()

0  1  2   3  4         5        6  7
0  0  3  1  22  1 -0.473674     7.25  S
1  1  1  0  38  1 -0.473674  71.2833  C
2  1  3  0  26  0 -0.473674    7.925  S
3  1  1  0  35  1 -0.473674     53.1  S
4  0  3  1  35  0 -0.473674     8.05  S

In [ ]:
pd.DataFrame(np_array_labeling).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       891 non-null    object
 1   1       891 non-null    object
 2   2       891 non-null    object
 3   3       891 non-null    object
 4   4       891 non-null    object
 5   5       891 non-null    object
 6   6       891 non-null    object
 7   7       889 non-null    object
dtypes: object(8)
memory usage: 55.8+ KB


#Use pandas

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
a, b = np.arange(10).reshape((5, 2)), range(5)
a, b

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), range(0, 5))

In [ ]:
train_test_split(a, b, random_state=2)

[array([[2, 3],
        [6, 7],
        [0, 1]]), array([[4, 5],
        [8, 9]]), [1, 3, 0], [2, 4]]

In [ ]:
train_test_split(a, b, random_state=2)

[array([[2, 3],
        [6, 7],
        [0, 1]]), array([[4, 5],
        [8, 9]]), [1, 3, 0], [2, 4]]

In [ ]:
train_test_split(a, b, random_state=3)

[array([[2, 3],
        [0, 1],
        [4, 5]]), array([[6, 7],
        [8, 9]]), [1, 0, 2], [3, 4]]

##get_dumies

###Titanic

In [ ]:
train[['Pclass','SibSp','Parch','Embarked', 'Sex']].tail()
# train
# train.info()

Pclass  SibSp  Parch Embarked     Sex
886       2      0      0        S    male
887       1      0      0        S  female
888       3      1      2        S  female
889       1      0      0        C    male
890       3      0      0        Q    male

In [ ]:
import pandas as pd
titanic_y = train['Survived']
titanic_x = train[['Pclass','SibSp','Parch','Embarked', 'Sex']]
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
temp = standardScaler.fit_transform(titanic_x[['SibSp','Parch']])
type(temp), temp.shape, type(titanic_x[['SibSp','Parch']].values), titanic_x[['SibSp','Parch']].values.shape, temp
# titanic_x.head()

(numpy.ndarray,
 (891, 2),
 numpy.ndarray,
 (891, 2),
 array([[ 0.43279337, -0.47367361],
        [ 0.43279337, -0.47367361],
        [-0.4745452 , -0.47367361],
        ...,
        [ 0.43279337,  2.00893337],
        [-0.4745452 , -0.47367361],
        [-0.4745452 , -0.47367361]]))

In [ ]:
titanic_x.loc[:,['SibSp','Parch']] = standardScaler.fit_transform(titanic_x[['SibSp','Parch']])
titanic_x.head()
# titanic_x['SibSp'] = temp[:,0]
# titanic_x.loc[:,['SibSp','Parch']]

SibSp     Parch  Sex_female  Embarked_C  Embarked_S  Pclass_1  Pclass_3
0  0.432793 -0.473674           0           0           1         0         1
1  0.432793 -0.473674           1           1           0         1         0
2 -0.474545 -0.473674           1           0           1         0         1
3  0.432793 -0.473674           1           0           1         1         0
4 -0.474545 -0.473674           0           0           1         0         1

In [ ]:
# titanic_x = pd.get_dummies(titanic_x, columns=['Sex', 'Embarked', 'Pclass'], drop_first=True)
titanic_x = pd.get_dummies(titanic_x, columns=['Sex', 'Embarked', 'Pclass'])
titanic_x.drop(columns=['Sex_male','Embarked_Q','Pclass_2'], axis=1, inplace=True)
titanic_x.head()

SibSp  Parch  Sex_female  Embarked_C  Embarked_S  Pclass_1  Pclass_3
0      1      0           0           0           1         0         1
1      1      0           1           1           0         1         0
2      0      0           1           0           1         0         1
3      1      0           1           0           1         1         0
4      0      0           0           0           1         0         1

####Logit with statmodel

In [ ]:
import statsmodels.api as sm
sm_constant = sm.add_constant(titanic_x)
# sm_constant
logit_model=sm.Logit(titanic_y,sm_constant)
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.455991
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  891
Model:                          Logit   Df Residuals:                      883
Method:                           MLE   Df Model:                            7
Date:                Mon, 25 May 2020   Pseudo R-squ.:                  0.3152
Time:                        04:53:34   Log-Likelihood:                -406.29
converged:                       True   LL-Null:                       -593.33
Covariance Type:            nonrobust   LLR p-value:                 8.587e-77
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.8244      0.374     -2.203      0.028      -1.558      -0.091
SibSp         -0.2109      0.

## Logistic Regreesion

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(titanic_x,titanic_y, test_size=0.2)
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train, y_train)
predictions = log.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)
log.predict([x_test.iloc[2]])
# result = log.predict([[0, 1, 1, 0, 1, 1, 0]])
x_test.iloc[2].shape, x_test.iloc[2].values, type(x_test.iloc[2]), x_test.shape, type(x_test), type([[0, 1, 1, 0, 1, 1, 0]]),

((7,),
 array([0, 0, 1, 0, 1, 1, 0]),
 pandas.core.series.Series,
 (179, 7),
 pandas.core.frame.DataFrame,
 list)

## MMLogit with iris

In [ ]:
from sklearn import datasets
iris_dataset = datasets.load_iris()
train_x = iris_dataset.data
train_y = iris_dataset.target

train_x.shape, train_y.shape, iris_dataset.target_names

((150, 4), (150,), array(['setosa', 'versicolor', 'virginica'], dtype='<U10'))

In [ ]:
df = pd.DataFrame(train_x, columns=iris_dataset.feature_names)
df['species'] = iris_dataset.target
df.to_csv('iris.csv')

In [ ]:
import statsmodels.api as sm
sm_constant = sm.add_constant(df[iris_dataset.feature_names])
logit_model=sm.MNLogit(df['species'],sm_constant)
# logit_model=sm.MNLogit(df['species'],df[iris_dataset.feature_names])
result=logit_model.fit(method='bfgs')
print(result.summary())

         Current function value: 0.057112
         Iterations: 35
         Function evaluations: 37
         Gradient evaluations: 37
                          MNLogit Regression Results                          
Dep. Variable:                species   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      140
Method:                           MLE   Df Model:                            8
Date:                Mon, 25 May 2020   Pseudo R-squ.:                  0.9480
Time:                        04:53:34   Log-Likelihood:                -8.5668
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 9.200e-63
        species=1       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 1.6444   1550.515      0.001      0.999 

/usr/local/lib/python3.6/dist-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))


              precision    recall  f1-score   support

           0       0.81      0.86      0.83       105
           1       0.78      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179



In [ ]:
from sklearn.utils.class_weight import compute_class_weight
Y_train = [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1 ,0]
class_weight = compute_class_weight('balanced', np.unique(Y_train), Y_train)
class_weight

array([0.72222222, 1.625     ])

In [ ]:
class_weight = compute_class_weight('balanced', np.unique(y_train), y_train)
class_weight

array([0.8018018 , 1.32835821])

###Telco-Customer-Churn

In [ ]:
import pandas as pd
telco_df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
# telco_df.head()
telco_df.

customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [ ]:
telco_df_y = telco_df['MonthlyCharges']
telco_df_x = telco_df[['tenure','gender', 'PaymentMethod']]
telco_df_x = pd.get_dummies(telco_df_x, columns=['gender', 'PaymentMethod'], drop_first=True)
telco_df_x.head()

tenure  ...  PaymentMethod_Mailed check
0       1  ...                           0
1      34  ...                           1
2       2  ...                           1
3      45  ...                           0
4       2  ...                           0

[5 rows x 5 columns]

####OLS with statmodel

In [ ]:
import statsmodels.api as sm
import numpy as np
sm_constant = sm.add_constant(telco_df_x)
estimate = sm.OLS(telco_df_y, sm_constant)
results = estimate.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:         MonthlyCharges   R-squared:                       0.211
Model:                            OLS   Adj. R-squared:                  0.210
Method:                 Least Squares   F-statistic:                     375.4
Date:                Mon, 25 May 2020   Prob (F-statistic):               0.00
Time:                        04:53:34   Log-Likelihood:                -33136.
No. Observations:                7043   AIC:                         6.628e+04
Df Residuals:                    7037   BIC:                         6.633e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                                            coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------

####LinearRegression with sklearn

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(telco_df_x, telco_df_y)
lr.score(telco_df_x, telco_df_y)

0.21057694900069235